Test

diff --git a/.github/workflows/gh-pages.yml b/.github/workflows/gh-pages.yml
--- a/.github/workflows/gh-pages.yml
+++ b/.github/workflows/gh-pages.yml
@@ -4,7 +4,12 @@ on:
     push:
         branches:
             - master
-            - documentation_*
+            - gh_pages_deploy
+        pull_request:
+            branches:
+                - master
+            paths:
+                - "docs/**"
 
 jobs:
     build:
@@ -15,6 +20,8 @@ jobs:
               uses: actions/checkout@v2.3.1 # If you're using actions/checkout@v2 you must set persist-credentials to false in most cases for the deployment to work correctly.
               with:
                 persist-credentials: false
+            - name: Test blub
+              run: echo ${{ GITHUB_EVENT_PATH }}
             - name: Install github-pages-deploy-action dependencies
               run: apt-get update && apt-get install -y rsync
             - name: Install eve and dependencies
@@ -57,6 +64,16 @@ jobs:
             - name: Print warning if deployment skipped
               run: echo "::warning::Documentation deployment skipped since the current commit is not the most recent of this branch"
               if: steps.check_if_most_recent_upstream.outputs.is_most_recent != 'TRUE'
+            #- name: Assemble target folder
+            #  shell: true
+            #  run: |
+            #    if [ "${{ github.event_name }" = "pull_request" ]; then
+            #      PR_ID=$(echo $GITHUB_REF | awk 'BEGIN { FS = "/" } ; { print $3 }')
+            #      if ! [[ "$PR_ID" =~ "^[0-9]+$" ]]; then
+            #        echo "Could not determine PR Id"
+            #        exit 1
+            #      fi
+            #      TARGET_FOLDER="docs/pr/${PR_ID}"
             - name: Deploy
               uses: JamesIves/github-pages-deploy-action@3.6.2
               if: steps.check_if_most_recent_upstream.outputs.is_most_recent == 'TRUE'
